language: node_js
node_js:
  - "node"
script:
  - git config --global alias.test "test"
  - yarn lint
  - yarn flow
  - yarn build
  - yarn prod
  - yarn jest
yarn: true
deploy:
  provider: npm
  email: "hsuting0106@gmail.com"
  api_key: $npm_token
  skip_cleanup: true
  on:
    tags: true
